<a href="https://colab.research.google.com/github/MathOlii/Repositorio_de_Aula/blob/main/02_Exerc%C3%ADcios_DataScience_MatheusBarbosa_6%C2%BAC_Noturno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1 - Exercicios de NumPy


In [ ]:
'''
1. Crie um array unidimensional de 50 elementos contendo numeros inteiros
aleatorios entre 10 e 100.
'''

import numpy as np

array = np.random.randint(10, 101, size=50)

print(array)

[24 79 37 65 52 83 85 33 39 13 29 83 75 56 25 16 99 70 16 14 69 60 63 78
 84 81 16 33 20 37 70 28 28 87 52 54 20 88 56 12 24 66 80 18 73 53 80 13
 47 70]


In [ ]:
'''
2. Gere uma matriz 4x4 com numeros inteiros de 1 a 16 e extraia a ultima
linha.
'''

import numpy as np

matriz = np.arange(1, 17).reshape(4, 4)

print("Matriz 4x4:")
print(matriz)

ultima_linha = matriz[-1]

print("\nÚltima linha:")
print(ultima_linha)

Matriz 4x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Última linha:
[13 14 15 16]


In [ ]:
'''
3. Crie um array de zeros com comprimento 15 e substitua os valores da 5ª
a 10ª posicao por 1.
'''
import numpy as np

array = np.zeros(15)

array[5:10] = 1

print("Array com zeros e 1 do 5ª a 10ª:")
print(array)

Array com zeros e 1 do 5ª a 10ª:
[0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


In [ ]:
'''
4. Gere um array de 100 numeros inteiros aleatorios e encontre a mediana e
a moda dos valores.
'''
import numpy as np
from scipy import stats

array = np.random.randint(1, 100, 100)

mediana = np.median(array)
moda = stats.mode(array, keepdims=True).mode[0]

print(f"Array: {array}")
print(f"\nMediana: {mediana}")
print(f"Moda: {moda}")

Array: [ 8 10 88 74 40 27 93 89 96 38 71 12  8 73 61 96 80 40  4 61 97 37 65 64
 51 64 47 63 53 89 11 56 55  1 29 28 94 53 18 55 69  3 42 33 32 14 24 42
 13 52  8 17  2 88  7 80 98 24  7  8 17  4 15  1 70 81 36 37 14 22  8 20
 21 39 79 69 76 66 57 43  7 25 12 88 63 85 81 32 84  6 78  8 63 61  6 65
 92 50  4 47]

Mediana: 42.5
Moda: 8


In [ ]:
'''
5. Crie um array de 20 elementos contendo numeros entre 1 e 100 e substitua
todos os valores multiplos de 3 por -3.
'''
import numpy as np

array = np.random.randint(1, 101, 20)

print("Array original:")
print(array)

array[array % 3 == 0] = -3

print("\nArray com -3:")
print(array)

Array original:
[ 35  19  86   6  79  59  36  24  82   7  92  90  67  51 100   2  83  65
  51  62]

Array com -3:
[ 35  19  86  -3  79  59  -3  -3  82   7  92  -3  67  -3 100   2  83  65
  -3  62]


In [ ]:
'''
6. Gere uma matriz 5x5 de numeros aleatorios entre 0 e 1 e encontre a soma
de cada coluna.
'''
import numpy as np

matriz = np.random.random((5, 5))

print("Matriz 5x5:")
print(matriz)

soma_colunas = np.sum(matriz, axis=0)

print("\nSoma de cada coluna:")
print(soma_colunas)

Matriz 5x5:
[[0.14375674 0.81184572 0.42000401 0.59778323 0.44754748]
 [0.91091914 0.09026339 0.35481959 0.34549426 0.75656695]
 [0.19529995 0.08362057 0.40403126 0.99981055 0.33234948]
 [0.11333952 0.18749068 0.44491521 0.33659653 0.44558   ]
 [0.00735482 0.69981708 0.12038056 0.98287111 0.01874544]]

Soma de cada coluna:
[1.37067017 1.87303743 1.74415064 3.26255568 2.00078935]


In [ ]:
'''
7. Crie dois arrays de numeros aleatorios e encontre a correlacao entre eles.
'''
import numpy as np

array1 = np.random.rand(10)
array2 = np.random.rand(10)

correlacao = np.corrcoef(array1, array2)[0, 1]

print("Array 1:", array1)
print("Array 2:", array2)
print("Correlação:", correlacao)

Array 1: [0.4652925  0.7867491  0.54830961 0.61252449 0.29687922 0.82926179
 0.7370948  0.7202835  0.18398556 0.86605903]
Array 2: [0.5060599  0.12606464 0.2434057  0.55448944 0.4514367  0.24147423
 0.38331818 0.52263477 0.7641068  0.0268097 ]
Correlação: -0.747117890015401


In [ ]:
'''
8. Gere uma matriz 3x3 com numeros inteiros aleatorios e eleve todos os seus
elementos ao quadrado.
'''
import numpy as np

matriz = np.random.randint(1, 10, (3, 3))

# Eleva todos os elementos ao quadrado
quadrado = matriz ** 2

print("Matriz original:")
print(matriz)

print("\nMatriz ao quadrado:")
print(quadrado)

Matriz original:
[[8 9 6]
 [9 4 2]
 [9 5 3]]

Matriz ao quadrado:
[[64 81 36]
 [81 16  4]
 [81 25  9]]


In [ ]:
'''
9. Crie um array com 10 numeros aleatorios e normalize seus valores entre 0
e 1.

normalizado = (array - array.min()) / (array.max() - array.min())

'''
import numpy as np

array = np.random.randint(1, 100, 10)

normalizado = (array - array.min()) / (array.max() - array.min())

print("Array original:")
print(array)

print("\nArray normalizado:")
print(normalizado)

Array original:
[57 33 76 51 55 25  9 53 37 30]

Array normalizado:
[0.71641791 0.35820896 1.         0.62686567 0.68656716 0.23880597
 0.         0.65671642 0.41791045 0.31343284]


In [ ]:
'''
10. Crie uma matriz identidade 6x6 e substitua a diagonal principal por valores
crescentes de 1 a 6.
'''
import numpy as np

matriz = np.eye(6, dtype=int)

matriz[np.diag_indices(6)] = np.arange(1, 7)

print(matriz)

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [ ]:
'''
11. Gere um array de 100 numeros inteiros e encontre o valor que mais se
repete no array.
'''
import numpy as np

array = np.random.randint(1, 10, 100)

numero = np.bincount(array).argmax()

print("Array:")
print(array)

print("\nNúmero que mais se repete:", numero)

Array:
[5 6 3 1 7 4 6 9 4 9 3 2 9 5 5 6 4 2 6 8 1 6 8 3 6 7 5 4 1 9 6 9 9 4 2 5 3
 8 8 5 4 3 8 4 6 1 8 1 7 6 3 7 5 4 2 2 1 2 2 6 8 6 6 8 8 4 6 6 4 2 9 6 8 8
 7 5 7 4 7 9 5 5 1 9 9 2 9 7 7 9 7 7 2 5 1 3 5 8 6 6]

Número que mais se repete: 6


In [ ]:
'''
12. Crie uma matriz 4x4 e substitua os valores da diagonal principal por 7.
'''
import numpy as np

matriz = np.random.randint(1, 10, (4, 4))

np.fill_diagonal(matriz, 7)

print(matriz)

[[7 1 5 4]
 [4 7 3 3]
 [9 1 7 1]
 [5 7 1 7]]


In [ ]:
'''
13. Crie um array contendo os 10 primeiros numeros pares e calcule sua soma
cumulativa.
'''
import numpy as np

array = np.arange(2, 21, 2)

soma = np.cumsum(array)

print("Números pares:")
print(array)

print("\nSoma cumulativa:")
print(soma)

Números pares:
[ 2  4  6  8 10 12 14 16 18 20]

Soma cumulativa:
[  2   6  12  20  30  42  56  72  90 110]


In [ ]:
'''
14. Calcule a diferenca entre dois arrays de numeros aleatorios de mesmo
comprimento e encontre a media das diferencas.
'''
import numpy as np

array1 = np.random.randint(1, 20, 10)
array2 = np.random.randint(1, 20, 10)

diferenca = array1 - array2

media = np.mean(diferenca)

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nDiferenças:")
print(diferenca)

print("\nMédia das diferenças:", media)

Array 1:
[ 7  4 11 19 14  2  4 11  1  7]

Array 2:
[ 1 17 15 12  4 11  2  6 13  6]

Diferenças:
[  6 -13  -4   7  10  -9   2   5 -12   1]

Média das diferenças: -0.7


In [ ]:
'''
15. Gere um array contendo 20 numeros e substitua todos os valores maiores
que 50 por 50.
'''
import numpy as np

array = np.random.randint(1,100,20)

print("Array Original:")
print(array)

array[array>50] = 50

print("\nArray com 50:")
print(array)

Array Original:
[75 22 52 39 24 91 83 91 18 70 26  3 17 79 21 15 74 68 10 20]

Array com 50:
[50 22 50 39 24 50 50 50 18 50 26  3 17 50 21 15 50 50 10 20]


In [ ]:
'''
16. Crie um array unidimensional e reorganize seus valores em uma matriz
3x4.
'''
import numpy as np

array = np.arange(1,13)

matriz = array.reshape(3,4)

print("Array:")
print(array)

print("\nMatriz 3x4:")
print(matriz)

Array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Matriz 3x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
'''
17. Gere uma matriz 4x4 de numeros inteiros aleatorios e multiplique cada
valor por sua posicao na matriz.

posicao = indice_linha + indice_coluna

posicao = 0 (0+0) 1 (0+1) 2 (0+2) 3 (0+3)
          1 (1+0) 2 (1+1) 3 (1+2) 4 (1+3)
          2 (2+0) 3 (2+1) 4 (2+2) 5 (2+3)
          3 (3+0) 4 (3+1) 5 (3+2) 6 (3+3)
'''
import numpy as np

matriz = np.random.randint(1,10,(4,4))

linhas,colunas = np.indices((4, 4))

matriz_multiplicada = matriz * (linhas + colunas)

print("Matriz original:")
print(matriz)

print("\nMatriz multiplicada:")
print(matriz_multiplicada)

Matriz original:
[[1 1 7 3]
 [2 6 5 8]
 [2 2 6 5]
 [2 2 8 4]]

Matriz multiplicada:
[[ 0  1 14  9]
 [ 2 12 15 32]
 [ 4  6 24 25]
 [ 6  8 40 24]]


In [ ]:
'''
18. Crie um array de 10 elementos contendo numeros entre 1 e 100 e substitua
todos os valores multiplos de 5 por 0.
'''
import numpy as np

array = np.random.randint(1,101,10)

print("Array Original:")
print(array)

array[array % 5 == 0] = 0

print("\nArray modificado:")
print(array)

Array Original:
[30 47 61  1 22  6 58 52 29 25]

Array modificado:
[ 0 47 61  1 22  6 58 52 29  0]


In [ ]:
'''
19. Crie dois arrays de numeros inteiros aleatorios de tamanho 20 e calcule o
angulo entre eles (produto escalar normalizado).
'''
import numpy as np

array1 = np.random.randint(1,10,20)
array2 = np.random.randint(1,10,20)

print("Array 1:")
print(array1)

print("Array 2:")
print(array2)

produto_escalar = np.dot(array1,array2)

norma_array1 = np.linalg.norm(array1)
norma_array2 = np.linalg.norm(array2)

angulo = np.arccos(produto_escalar / (norma_array1 * norma_array2))

print("\nProduto Escalar:", produto_escalar)
print("Angulo entre os arrays em radianos:", angulo)

Array 1:
[4 1 5 9 8 4 5 2 6 7 9 7 2 8 2 1 9 2 5 3]
Array 2:
[6 5 3 6 9 7 5 8 2 4 3 6 4 1 3 3 1 3 6 2]

Produto Escalar: 424
Angulo entre os arrays em radianos: 0.6925719641428866


In [ ]:
'''
20. Crie uma matriz de numeros inteiros e encontre o valor mınimo de cada
linha.
'''
import numpy as np

matriz = np.random.randint(1,101,(5,5))

print("Matriz:")
print(matriz)

minimo_por_linha = np.min(matriz,axis=1)

print("\nValor mínimo de cada linha:")
print(minimo_por_linha)

Matriz:
[[81 90 88 32 85]
 [95 73 15 92 97]
 [83 69 47 30  3]
 [78 94 40 26  2]
 [70 62 12 69 65]]

Valor mínimo de cada linha:
[32 15  3  2 12]


# 2 - Exercıcios de SciPy

In [ ]:
'''
1. Calcule a integral da funcao f(x) = x**2 sin(x) no intervalo de 0 a π.
'''
import numpy as np
from scipy.integrate import quad

def f(x):
    return x**2 * np.sin(x)

resultado = quad(f, 0, np.pi)

print(resultado[0])

5.869604401089359


In [ ]:
'''
2. Resolva a equacao diferencial dy/dx = x − y, com y(0) = 1, no intervalo de 0
a 10.
'''
import numpy as np
from scipy.integrate import solve_ivp

def f(x, y):
    return x - y

resultado = solve_ivp(f, [0, 10], [1])

print(resultado.y[0])

[1.         0.92029381 0.7131988  1.04582535 1.74879205 2.83567181
 4.35139245 6.43481768 9.00046149]


In [ ]:
'''
3. Encontre as raızes da funcao f(x) = x**4 − 3x**3 + 2 utilizando SciPy.
'''
import numpy as np
from scipy.optimize import root

def f(x):
  return x**4 - 3*x**3 + 2

resultado = root(f,1)

print("Raiz:", resultado.x[0])

Raiz: 1.0


In [ ]:
'''
4. Use a funcao de otimizacao de SciPy para maximizar f(x) = −x**2+ 4x+ 1
'''
from scipy.optimize import minimize

def f(x):
  return -(x**2) + 4*x + 1

resultado = minimize(lambda x: -f(x), 0)

print("Valor de x:", resultado.x[0])
print("Valor maximo:", f(resultado.x[0]))

Valor de x: 2.000000026187685
Valor maximo: 4.999999999999999


In [ ]:
'''
5. Calcule a transformada de Fourier de um sinal composto de sin(2πt) e
cos(4πt).
'''
import numpy as np
from scipy.fft import fft, fftfreq

t = np.linspace(0,1,1000)

sinal = np.sin(2 * np.pi * t) + np.cos(4 * np.pi * t)

transf = fft(sinal)

frenq = fftfreq (len(t), t[1] - t[0])

for i in range(len(frenq)):
  if abs(transf[i]) > 100:
    print("frenquencia:", frenq[i])

frenquencia: 0.9989999999999999
frenquencia: 1.9979999999999998
frenquencia: -1.9979999999999998
frenquencia: -0.9989999999999999


In [ ]:
'''
6. Encontre a matriz inversa de uma matriz 5x5 de numeros aleatorios.
'''
import numpy as np
from scipy.linalg import inv

matriz = np.random.randint(1,10,(5,5))

inversa = inv(matriz)

print("Matriz Original:")
print(matriz)

print("\nMatriz Inversa:")
print(inversa)

Matriz Original:
[[6 6 1 2 3]
 [9 6 2 2 1]
 [6 8 7 7 3]
 [3 6 5 5 7]
 [2 9 8 5 2]]

Matriz Inversa:
[[-0.19295559  0.24400204 -0.0229709   0.07605921 -0.06431853]
 [ 0.381317   -0.21235324 -0.02603369 -0.158244    0.12710567]
 [-0.56814701  0.42215416 -0.23430322  0.24247065  0.143951  ]
 [ 0.32924962 -0.4216437   0.49157734 -0.22766718 -0.22358346]
 [-0.07350689  0.07708014 -0.15160796  0.23532414 -0.0245023 ]]


In [ ]:
'''
7. Use a funcao de interpolacao cubica de SciPy para interpolar os dados
(0, 0),(1, 2),(2, 3),(3, 5),(4, 4).
'''
import numpy as np
from scipy.interpolate import CubicSpline

x = np.array([0, 1, 2, 3, 4])
y = np.array([0, 2, 3, 5, 4])

funcao = CubicSpline(x, y)

novos_x = np.linspace(0, 4, 10)

novos_y = funcao(novos_x)

print("Valores de x:")
print(novos_x)

print("\nValores interpolados:")
print(novos_y)

Valores de x:
[0.         0.44444444 0.88888889 1.33333333 1.77777778 2.22222222
 2.66666667 3.11111111 3.55555556 4.        ]

Valores interpolados:
[0.         1.23639689 1.89117513 2.27160494 2.68495656 3.42203932
 4.39506173 5.13763146 5.16689529 4.        ]


In [ ]:
'''
8. Resolva o sistema de equacoes 3x + 2y = 5 e x + 4y = 6.
'''
import numpy as np
from scipy.linalg import solve

A = np.array([
    [3, 2],
    [1, 4]
])

b = np.array([5, 6])

resultado = solve(A, b)

print("x =", resultado[0])
print("y =", resultado[1])

x = 0.7999999999999999
y = 1.3


In [ ]:
'''
9. Ajuste uma curva quadratica aos pontos (1, 2),(2, 4),(3, 5),(4, 7),(5, 8).
'''
import numpy as np
from scipy.optimize import curve_fit

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 7, 8])

def funcao(x, a, b, c):
    return a*x**2 + b*x + c

parametros, _ = curve_fit(funcao, x, y)

print("a =", parametros[0])
print("b =", parametros[1])
print("c =", parametros[2])

a = -0.07142857142857162
b = 1.9285714285714297
c = 0.19999999999999807


In [ ]:
'''
10. Calcule a integral dupla da funcao f(x, y) = xy + x**2 no intervalo [0, 2]
para x e [0, 1] para y.
'''
from scipy.integrate import dblquad

def f(y, x):
    return x * y + x**2

resultado = dblquad(f, 0, 2, 0, 1)

print("Resultado:", resultado[0])

Resultado: 3.666666666666667


In [ ]:
'''
11. Encontre os autovalores e autovetores de uma matriz 4x4 de numeros
inteiros aleatorios.
'''
import numpy as np
from scipy.linalg import eig

matriz = np.random.randint(1, 10, (4, 4))

autovalores, autovetores = eig(matriz)

print("Matriz:")
print(matriz)

print("\nAutovalores:")
print(autovalores)

print("\nAutovetores:")
print(autovetores)

Matriz:
[[6 3 2 7]
 [9 4 6 5]
 [3 4 4 3]
 [1 8 3 3]]

Autovalores:
[17.98703721+0.j         -1.18927213+3.55658094j -1.18927213-3.55658094j
  1.39150704+0.j        ]

Autovetores:
[[-0.48804714+0.j         -0.38801286-0.33683954j -0.38801286+0.33683954j
   0.56589195+0.j        ]
 [-0.64039485+0.j         -0.35137842+0.35243813j -0.35137842-0.35243813j
   0.25928811+0.j        ]
 [-0.38463569+0.j          0.10081134-0.00784122j  0.10081134+0.00784122j
  -0.73302451+0.j        ]
 [-0.45139762+0.j          0.69143424+0.j          0.69143424-0.j
  -0.27424634+0.j        ]]


In [ ]:
'''
12. Resolva a equacao e**x − x**2 = 0 para encontrar a raiz mais proxima de
x = 1.
'''
import numpy as np
from scipy.optimize import root

def f(x):
    return np.exp(x) - x**2

resultado = root(f, 1)

print("Raiz:", resultado.x[0])

Raiz: -0.7034674224983917


In [ ]:
'''
13. Calcule o determinante de uma matriz 6x6 de numeros aleatorios entre
-10 e 10.
'''
import numpy as np
from scipy.linalg import det

matriz = np.random.randint(-10, 11, (6, 6))

resultado = det(matriz)

print("Matriz:")
print(matriz)

print("\nDeterminante:", resultado)

Matriz:
[[ -6  -1 -10   1   1   6]
 [  8   2   5   5  -2   5]
 [ -6  -1   8   7  -7  -6]
 [ 10  -1  -9   5  -9   1]
 [ -6  -5   7  -7  -4   8]
 [  9  -5   8  -4   9   2]]

Determinante: 3206966.0000000005


In [ ]:
'''
14. Utilize a funcao de otimizacao multivariada para minimizar
f(x, y) = (x−2)**2 + (y − 3)**2.
'''
from scipy.optimize import minimize

def f(valores):
    x, y = valores
    return (x - 2)**2 + (y - 3)**2

inicio = [0, 0]

resultado = minimize(f, inicio)

print("x =", resultado.x[0])
print("y =", resultado.x[1])
print("Valor mínimo =", resultado.fun)

x = 1.9999999892076392
y = 2.9999999917462903
Valor mínimo = 1.84598775337616e-16


In [ ]:
'''
15. Calcule a transformada de Fourier inversa de um sinal complexo gerado
aleatoriamente.
'''
import numpy as np
from scipy.fft import fft, ifft

sinal = np.random.rand(10) + 1j * np.random.rand(10)

transf = fft(sinal)

resultado = ifft(transf)

print("Sinal original:")
print(sinal)

print("\nTransformada de Fourier:")
print(transf)

print("\nTransformada inversa:")
print(resultado)

Sinal original:
[0.58229262+0.96372642j 0.10921496+0.08458533j 0.19496035+0.56548527j
 0.55441497+0.61366394j 0.42439702+0.29149905j 0.66164953+0.09886651j
 0.29492704+0.82229463j 0.91491484+0.87040925j 0.67062771+0.6866975j
 0.95749543+0.35027302j]

Transformada de Fourier:
[ 5.36489449+5.34750092j -0.81250201+1.46168009j  0.23866585+0.32506484j
 -0.2336106 +1.45440839j  0.54746612+1.1204332j  -1.03048499+1.31190482j
  0.49361235+0.19008021j  0.83707488+1.07012311j -0.42492801-1.67011455j
  0.84273817-0.97381688j]

Transformada inversa:
[0.58229262+0.96372642j 0.10921496+0.08458533j 0.19496035+0.56548527j
 0.55441497+0.61366394j 0.42439702+0.29149905j 0.66164953+0.09886651j
 0.29492704+0.82229463j 0.91491484+0.87040925j 0.67062771+0.6866975j
 0.95749543+0.35027302j]


In [ ]:
'''
16. Resolva a equacao diferencial de segunda ordem d**2y/dx**2 +y = 0, com
condicoes iniciais y(0) = 1 e y′(0) = 0.
'''
import numpy as np
from scipy.integrate import solve_ivp

def f(x, y):
    return [y[1], -y[0]]

inicio = [1, 0]

resultado = solve_ivp(f, [0, 10], inicio)

print("Valores de x:")
print(resultado.t)

print("\nValores de y:")
print(resultado.y[0])

Valores de x:
[0.00000000e+00 9.99000999e-04 1.09890110e-02 1.10889111e-01
 7.60150558e-01 1.69346562e+00 2.68189213e+00 3.66249862e+00
 4.57787220e+00 5.57710241e+00 6.53562405e+00 7.50732249e+00
 8.49647637e+00 9.42948990e+00 1.00000000e+01]

Valores de y:
[ 1.          0.9999995   0.99993962  0.9938581   0.72470976 -0.12260765
 -0.89641298 -0.86688128 -0.13300558  0.76180951  0.96779275  0.33780842
 -0.60103767 -0.99985842 -0.83754524]


In [ ]:
'''
17. Encontre a raiz cubica de 27 utilizando SciPy.
'''
from scipy.optimize import root_scalar

def f(x):
    return x**3 - 27

resultado = root_scalar(f, bracket=[0, 5])

print("Raiz cúbica de 27:", resultado.root)

Raiz cúbica de 27: 3.0


In [ ]:
'''
18. Interpole os valores de uma funcao f(x) = x**2 nos pontos [1, 2, 3, 4, 5]
utilizando spline cubica.
'''
import numpy as np
from scipy.interpolate import CubicSpline

x = np.array([1, 2, 3, 4, 5])

y = x**2

spline = CubicSpline(x, y)

novos_x = np.array([1.5, 2.5, 3.5, 4.5])

novos_y = spline(novos_x)

print("Novos pontos:")
print(novos_x)

print("\nValores interpolados:")
print(novos_y)

Novos pontos:
[1.5 2.5 3.5 4.5]

Valores interpolados:
[ 2.25  6.25 12.25 20.25]


In [ ]:
'''
19. Realize a transformada de Fourier de um sinal discreto composto de senos
e cossenos.
'''
import numpy as np
from scipy.fft import fft

x = np.arange(20)

sinal = np.sin(2 * np.pi * x / 10) + np.cos(2 * np.pi * x / 5)

resultado = fft(sinal)

print("Sinal:")
print(sinal)

print("\nTransformada de Fourier:")
print(resultado)

Sinal:
[ 1.          0.89680225  0.14203952  0.14203952  0.89680225  1.
 -0.27876826 -1.76007351 -1.76007351 -0.27876826  1.          0.89680225
  0.14203952  0.14203952  0.89680225  1.         -0.27876826 -1.76007351
 -1.76007351 -0.27876826]

Transformada de Fourier:
[ 9.99200722e-16-0.00000000e+00j -1.33226763e-15+1.33226763e-15j
 -2.66453526e-15-1.00000000e+01j -1.77635684e-15+0.00000000e+00j
  1.00000000e+01-6.21724894e-15j  1.77635684e-15+7.77156117e-16j
  8.88178420e-16-1.77635684e-15j  8.88178420e-16+8.88178420e-16j
  0.00000000e+00+0.00000000e+00j  1.33226763e-15+4.44089210e-16j
 -9.99200722e-16-0.00000000e+00j  1.33226763e-15-4.44089210e-16j
  0.00000000e+00-0.00000000e+00j  8.88178420e-16-8.88178420e-16j
  8.88178420e-16+1.77635684e-15j  1.77635684e-15-7.77156117e-16j
  1.00000000e+01+6.21724894e-15j -1.77635684e-15-0.00000000e+00j
 -2.66453526e-15+1.00000000e+01j -1.33226763e-15-1.33226763e-15j]


In [ ]:
'''
20. Resolva um sistema de equacoes lineares com tres variaveis utilizando
SciPy.
'''
import numpy as np
from scipy.linalg import solve

A = np.array([
    [1, 1, 1],
    [2, 1, 1],
    [1, 2, 1]
])

b = np.array([6, 7, 8])

resultado = solve(A, b)

print("x =", resultado[0])
print("y =", resultado[1])
print("z =", resultado[2])

x = 1.0
y = 2.0
z = 2.9999999999999996
